default: &default
  adapter: postgresql
  encoding: utf8
  host: postgres
  port: 5432
  username: testributor
  password: testributor
  pool: 5

development:
  <<: *default
  database: 'katana_dev'

test:
  <<: *default
  database: 'katana_test'
